language: rust
script:
  - cargo build --verbose --all --target wasm32-unknown-emscripten
after_success: >
  cargo doc --no-deps --all \

  && echo '<meta http-equiv=refresh content=0;url=emscripten/index.html>' >
  target/doc/index.html && \

  sudo pip install ghp-import && \

  ghp-import -n target/doc && \

  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
