language: rust
cache:
  cargo: true
install:
  - cargo install cargo-update; true
  - cargo install-update -i cargo-update
  - cargo install-update -i cargo-web
script:
  - (cd emscripten-sys && cargo web test --target wasm32-unknown-emscripten)
  - (cd emscripten && cargo web test --target wasm32-unknown-emscripten)
before_deploy:
  - cargo doc --no-deps --all --target wasm32-unknown-emscripten
  - >-
    echo '<meta http-equiv=refresh content=0;url=emscripten/index.html>' >
    target/wasm32-unknown-emscripten/doc/index.html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $TOKEN
  keep-history: true
  local-dir: target/wasm32-unknown-emscripten/doc
  on:
    branch: master
