language: rust
before-script:
  - rustup target add wasm32-unknown-emscripten
script:
  - cargo build --verbose --all --target wasm32-unknown-emscripten
before-deploy:
  - cargo doc --no-deps --all
  - >-
    echo '<meta http-equiv=refresh content=0;url=emscripten/index.html>' >
    target/doc/index.html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $TOKEN
  keep-history: true
  local-dir: target/doc
  on:
    branch: master
